#python script_fig4_run_resolution_sweep.py narrow_search_factor default
#python script_fig4_run_resolution_sweep.py narrow_search_factor barcode_ablation
#python script_fig4_run_resolution_sweep.py narrow_search_factor place_field_ablation
#python script_fig4_run_resolution_shuffle_sweep.py narrow_search_factor default

python script_fig4_run_resolution_sweep.py weight_var default
python script_fig4_run_resolution_sweep.py narrow_search_factor prediction
python script_fig4_run_resolution_sweep.py narrow_search_factor gaussian
# Capacity
